export const UserCheckIns =
[
    {
        key:1,
        url:"https://s3.us-east-2.amazonaws.com/swiftmile-app-assets/app-images/map-pois/calibrationdrawing.png",
        date:"",
        venue:""

    },
    {
        key:2,
        url:"https://s3.us-east-2.amazonaws.com/swiftmile-app-assets/app-images/map-markers/marker-tapcade.png",
        date:"",
        venue:""
    },
    {
        key:3,
        url:"https://s3.us-east-2.amazonaws.com/swiftmile-app-assets/app-images/map-markers/marker-patspubdrawing.png",
        date:"",
        venue:""
    },
    {
        key:4,
        url:"https://s3.us-east-2.amazonaws.com/swiftmile-app-assets/app-images/map-markers/marker-grain2glass.png",
        date:"",
        venue:""
    },
    {
        key:5,
        url:"https://s3.us-east-2.amazonaws.com/swiftmile-app-assets/app-images/map-pois/calibrationdrawing.png",
        date:"",
        venue:""
    },
    {
        key:6,
        url:"https://s3.us-east-2.amazonaws.com/swiftmile-app-assets/app-images/map-markers/marker-tapcade.png",
        date:"",
        venue:""
    },
    {
        key:7,
        url:"https://s3.us-east-2.amazonaws.com/swiftmile-app-assets/app-images/map-markers/marker-patspubdrawing.png",
        date:"",
        venue:""
    },
    {
        key:8,
        url:"https://s3.us-east-2.amazonaws.com/swiftmile-app-assets/app-images/map-markers/marker-grain2glass.png",
        date:"",
        venue:""
    },
    {
        key:9,
        url:"https://s3.us-east-2.amazonaws.com/swiftmile-app-assets/app-images/map-pois/calibrationdrawing.png",
        date:"",
        venue:""
    },
    {
        key:10,
        url:"https://s3.us-east-2.amazonaws.com/swiftmile-app-assets/app-images/map-markers/marker-tapcade.png",
        date:"",
        venue:""
    },
    {
        key:11,
        url:"https://s3.us-east-2.amazonaws.com/swiftmile-app-assets/app-images/map-markers/marker-patspubdrawing.png",
        date:"",
        venue:""
    },
    {
        key:12,
        url:"https://s3.us-east-2.amazonaws.com/swiftmile-app-assets/app-images/map-markers/marker-grain2glass.png",
        date:"",
        venue:""
    }

];