
#source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

#install! 'cocoapods', :deterministic_uuids => false

target 'NKCGo' do

#  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
#  pod 'React', :path => '../node_modules/react-native'


  pod 'GoogleMaps'
#  pod 'react-native-maps', :path => '../node_modules/react-native-maps'
#  pod 'react-native-google-maps', :path => '../node_modules/react-native-maps'
  
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "react-native-google-maps"
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
    
    if target.name == "React"
      target.remove_from_project
    end
  end
end
